server:
  port: 8080
  servlet:
    context-path: /
spring:
  freemarker:
    suffix: .html
  datasource:
    username: root
    password: 603894
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
